### ISSUE TITLE
Request: add built-in Master System/Game Gear support

### ISSUE THREAD

**Issue by user020** [veikkos/omega-kernel#3]
Could support be added to automatically open .sms and .gg files that are run from the EZFlash Omega menu in SMSAdvance as per the fork of the kernel linked below?

https://github.com/atomicretronl/omega-kernel/releases

**Comment by veikkos** [comment]
Thanks for the suggestion. I think for now I'm not going to integrate other systems. Feel free to fork and build your own kernel if you like. :)
