### ISSUE TITLE
Swap Quick start Key

### ISSUE THREAD

**Issue by Wapameepto** [veikkos/omega-kernel#5]
Hi, 
is it possible to swap the Quick start keys to the following?
 
Keep L +A pressed when booting to start last game in NOR
Keep L pressed when booting to start last played SD-card game

Usually I don´t use the NOR. And pressing only one button is easier.

**Comment by veikkos** [comment]
I think users might have gotten used to how it works now. Some other kernels also have L for NOR games, so I think for now I'm going with that to avoid confusion. I've kept my favorite game on NOR so for me it now feels natural.

Thanks for the comment!
